finalize formatting in C++ (#240)
- Enforce formatting for C++ files as part of the commit hook and test pipeline. (and it works [here](https://github.com/troyvvgroup/quemb/actions/runs/18782916862/job/53593553319?pr=240) )

- Changed `clang-format` fules for C++ files and make it more similar to ruff in python to have a more consistent look and feel across languages.

- Additionally the pre-commit hook emits more info now when failing.

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -24,13 +24,29 @@ if ! command -v ruff >/dev/null 2>&1; then
     exit 1
 else
     if ! ruff format --diff `git rev-parse --show-toplevel` >/dev/null 2>&1; then
+        ruff format --diff `git rev-parse --show-toplevel`
+        >&2 echo
         >&2 echo "There are problems with PEP8-compliance."
         >&2 echo 'You can check yourself by executing "ruff format --diff `git rev-parse --show-toplevel`"'
         exit 1
     fi
     if ! ruff check `git rev-parse --show-toplevel` >/dev/null 2>&1; then
+        ruff check `git rev-parse --show-toplevel`
+        >&2 echo
         >&2 echo "There are problems in the code."
         >&2 echo 'You can check yourself by executing "ruff check `git rev-parse --show-toplevel`"'
+        exit 1
+    fi
+fi
+
+# Unlike ruff we do not force people to install clang-format as
+# many developers won't touch the C++ parts anyway.
+if command -v clang-format >/dev/null 2>&1; then
+    if ! find src -type f -regex '.*\.\(cpp\|hpp\|cc\|h\)$' -print0 \
+        | xargs -0 -r clang-format --dry-run --Werror >/dev/null; then
+        >&2 echo "There are problems in the C++ code's formatting."
+        >&2 echo "You can check yourself by executing:"
+        >&2 echo "find src -regex '.*\.\(cpp\|hpp\|cc\|h\)$' -exec clang-format --dry-run --Werror {} \;"
         exit 1
     fi
 fi
